### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by eselvam** [ansible-collections/netapp.ontap#43]
we have playbook with below: when executing the playbook in Awx with custom netapp ee, we are getting: urllib.error.HTTPError: HTTP Error 401: Unauthorized. Kindly help us to resolve it.
-
  name: "Get Vserver List"
  netapp.ontap.na_ontap_command:
    hostname: "{{ hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    command: ['version']

full stack trace from job run:
TASK [Get Vserver List] ********************************************************
task path: /runner/project/vserver.yml:8
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: runner
<localhost> EXEC /bin/sh -c 'echo ~runner && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/runner/.ansible/tmp `"&& mkdir "` echo /home/runner/.ansible/tmp/ansible-tmp-1642868997.2556906-24-96642586806329 `" && echo ansible-tmp-1642868997.2556906-24-96642586806329="` echo /home/runner/.ansible/tmp/ansible-tmp-1642868997.2556906-24-96642586806329 `" ) && sleep 0'
Using module file /runner/requirements_collections/ansible_collections/netapp/ontap/plugins/modules/na_ontap_command.py
<localhost> PUT /home/runner/.ansible/tmp/ansible-local-18r8julljj/tmpoxha3kpi TO /home/runner/.ansible/tmp/ansible-tmp-1642868997.2556906-24-96642586806329/AnsiballZ_na_ontap_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/runner/.ansible/tmp/ansible-tmp-1642868997.2556906-24-96642586806329/ /home/runner/.ansible/tmp/ansible-tmp-1642868997.2556906-24-96642586806329/AnsiballZ_na_ontap_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/runner/.ansible/tmp/ansible-tmp-1642868997.2556906-24-96642586806329/AnsiballZ_na_ontap_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/runner/.ansible/tmp/ansible-tmp-1642868997.2556906-24-96642586806329/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_netapp.ontap.na_ontap_command_payload_x1t9whuy/ansible_netapp.ontap.na_ontap_command_payload.zip/ansible_collections/netapp/ontap/plugins/module_utils/netapp.py", line 549, in invoke_elem
    response = self._opener.open(request)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_netapp.ontap.na_ontap_command_payload_x1t9whuy/ansible_netapp.ontap.na_ontap_command_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_command.py", line 183, in run_command
  File "/usr/local/lib/python3.8/site-packages/netapp_lib/api/zapi/zapi.py", line 292, in invoke_successfully
    result = self.invoke_elem(na_element, enable_tunneling)
  File "/tmp/ansible_netapp.ontap.na_ontap_command_payload_x1t9whuy/ansible_netapp.ontap.na_ontap_command_payload.zip/ansible_collections/netapp/ontap/plugins/module_utils/netapp.py", line 551, in invoke_elem
    raise zapi.NaApiError(exc.code, exc.reason)
netapp_lib.api.zapi.zapi.NaApiError: NetApp API failed. Reason - 401:Unauthorized
fatal: [localhost]: FAILED! => {

**Comment by lonico** [comment]
Should be addressed in Slack.  Not a code issue.
