### ISSUE TITLE
Can't install certificate

### ISSUE THREAD

**Issue by RogelioCodes** [ansible-collections/netapp.ontap#53]
### Summary

Hello, I am trying to install a certificate using your module and I am getting a failure without an error message. I am not sure who to reach out to about this. I've tried poking around and figuring it out myself but I have hit a wall.
 

 

 
 
 

### Component Name

na_ontap_security_certificates

### Ansible Version

```console
$ ansible --version
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: u'list' (choose from 'init', 'build', 'publish', 'install')

$ ansible-galaxy collection
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: u'list' (choose from 'init', 'build', 'publish', 'install')
```

### ONTAP Version

```console
sridharc-vsim34::> version
NetApp Release 9.8P7: Tue Sep 14 18:38:58 UTC 2021
```

### Playbook

```console
Playbook:
 
---
- name: show certs
   hosts: localhost
   gather_facts: true
   connection: local
   collections:
     - netapp.ontap.na_ontap_security_certificates
   vars:
       https: true
       validate_certs: false
   tasks:
   - name: show certs
     na_ontap_security_certificates:
       #hostname: "{{ netapp_hostname
       hostname: "{{ netapp_hostname }}"
       username: "{{ netapp_username }}"
       password: "{{ netapp_password }}"
       common_name: "{{ ontap_cert_common_name }}"
       name: "{{ ontap_cert_name }}"
       type: "{{ type }}"
       svm: "{{ vserver }}"
       private_key: |
         -----BEGIN PRIVATE KEY-----
         -----END PRIVATE KEY------
       public_certificate: |
         -----BEGIN CERTIFICATE-----
                ….
         -----END CERTIFICATE-----
```

### Steps to Reproduce

```yaml (paste below)

```
commands:
 ansible-playbook security_cert_install_v2.yml -e 'netapp_hostname=REDACTED netapp_username=REDACTED netapp_password=REDACTED vserver=testvserver type=server ontap_cert_common_name=test01.domain.com ontap_cert_name=test01.domain.com ' -vvv

### Expected Results

I expected the certificate to be installed. I have done this manually using all of the same parameters, I just can't get it to work through the ansible module.

### Actual Results

```console
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert_filepath": null,
            "common_name": "REDACTED",
            "expiry_time": null,
            "feature_flags": {},
            "hash_function": null,
            "hostname": "REDACTED",
            "http_port": null,
            "https": false,
            "ignore_name_if_not_supported": true,
            "intermediate_certificates": null,
            "key_filepath": null,
            "key_size": null,
            "name": "REDACTED",
            "ontapi": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "private_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "public_certificate": "-----BEGIN CERTIFICATE----- \n
             -----END CERTIFICATE-----\n",
            "signing_request": null,
            "state": "present",
            "svm": "REDACTED",
            "type": "server",
            "use_rest": "auto",
            "username": "myuser",
            "validate_certs": true
        }
    },
    "msg": null
}
```

**Comment by RogelioCodes** [comment]
I have since updated my module to the latest collection(netapp.ontap:21.17.3)

I now get an error saying:

  ```
    "msg": "na_ontap_security_certificates only supports REST, and requires ONTAP 9.6 or later. - HTTPSConnectionPool(host='test01', port=443): Max retries exceeded with url: /api/cluster?fields=version (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:618)'),))"

**Comment by lonico** [comment]
The initial issue was fixed in 21.16.0.  The error message was wrongly generated when REST was not available.  It was not an issue with na_ontap_security_certificates but a utility function it depends on.

So most likely, you experienced the same SSL issue.

This first part of the message is easy to interpret.  Since we cannot reach your system, we cannot confirm it supports REST.

The second part is more difficult:
SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:618)'),))

This is not something that comes from our module, and I don’t think it comes from ONTAP, so I’d suspect a networking issue.   The first thing that comes to mind is a proxy issue.  Are you using a proxy by any chance?

**Comment by lonico** [comment]
A bit if googling also suggests to check the version of OpenSSL.  Could you try this with python 2.7:

```
from urllib2 import urlopen
urlopen('https://www.howsmyssl.com/a/check').read()
```

from https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol

**Comment by RogelioCodes** [comment]
> A bit of googling also suggests to check the version of OpenSSL. Could you try this with python 2.7:
> 
> ```
> from urllib2 import urlopen
> urlopen('https://www.howsmyssl.com/a/check').read()
> ```
> 
> from https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol

heres what i get: 
```
$ python test5.py
Traceback (most recent call last):
  File "test5.py", line 2, in <module>
    urlopen('https://www.howsmyssl.com/a/check').read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by RogelioCodes** [comment]
> The initial issue was fixed in 21.16.0. The error message was wrongly generated when REST was not available. It was not an issue with na_ontap_security_certificates but a utility function it depends on.
> 
> So most likely, you experienced the same SSL issue.
> 
> This first part of the message is easy to interpret. Since we cannot reach your system, we cannot confirm it supports REST.
> 
> The second part is more difficult: SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:618)'),))
> 
> This is not something that comes from our module, and I don’t think it comes from ONTAP, so I’d suspect a networking issue. The first thing that comes to mind is a proxy issue. Are you using a proxy by any chance?

Hello, I actually think I have an idea of whats happening. We’re updating an expiring signed certificate, which requires the deletion of an existing certificate, which stops the ssl service. If the service stops every time a certificate is deleted, how am I supposed to install the new one. The SSL service is down after deleting.

**Comment by lonico** [comment]
So the new issue is that you cannot use certificate authentication after deleting the certificate.  But how do you renew a certificate?

A few options:

1. You could install the new certificate with a new name.  We support both a `name` and a `common_name`.   Since this a different certificate, it seems a new name would help.  name is not supported by ONTAP 9.6 or 9.7, but was added in 9.8.  once the new certificate is installed, the old one can be safely deleted.
2. if you want to delete the certificate first, you can install the new one using username/password authentication.  Though it defeats the purpose of using SSL authentication.
